### GET / 

GET http://localhost:5000

### register 
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword"
}
### login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "newuser",
  "password": "newpassword"
}

### get todo endpoint{protected}
### get todo endpoint (protected)
GET http://localhost:5000/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzUzMzUxOTMyLCJleHAiOjE3NTM0MzgzMzJ9.tmatNTeu96u-RW7fEIGzHLwr7NhiDBkMCku0_g2xzxc
### create todo endpoint{protected}
### Creates a new todo POST /TODOS (protected)
POST http://localhost:5000/todos 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzUzMzUxOTMyLCJleHAiOjE3NTM0MzgzMzJ9.tmatNTeu96u-RW7fEIGzHLwr7NhiDBkMCku0_g2xzxc

{

"task": "Finish coding the projects"

}

### update todo endpoint{protected}
### Updates an existing todo PUT /TODOS/{id} (protected)
PUT http://localhost:5000/todos/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzUzMzUxOTMyLCJleHAiOjE3NTM0MzgzMzJ9.tmatNTeu96u-RW7fEIGzHLwr7NhiDBkMCku0_g2xzxc

{

  "completed": 1
  
}

###delete todo endpoint{protected}
### Deletes an existing todo DELETE /TODOS/{id} (protected)
DELETE http://localhost:5000/todos/4
Content-Type: application/json
Authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzUzMzUxOTMyLCJleHAiOjE3NTM0MzgzMzJ9.tmatNTeu96u-RW7fEIGzHLwr7NhiDBkMCku0_g2xzxc